[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && ./node_modules/.bin/prisma generate && ./node_modules/.bin/tsc"]

[start]
cmd = "cd server && ./node_modules/.bin/prisma migrate deploy && node dist/index.js"
