[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && ./node_modules/.bin/prisma generate && npm run build"

[deploy]
startCommand = "cd server && ./node_modules/.bin/prisma migrate deploy && node dist/index.js"
restartPolicyType = "on_failure"
